# ============================================================
# Retrieve NO_CONN_001's pre-computed derived caches (~2GB) from the
# repository's GitHub Release assets.
#
# WHY THESE AREN'T IN THE REPO: rebuilding them from scratch is 20+ hours
# of compute (Østlandet alone ~13h), so they are published rather than
# regenerated by every collaborator. They are not committed because
# several exceed GitHub's 100MB per-file hard limit, and 2GB in git
# history would make every clone slow. See README's "Cache vs. real
# compute".
#
# Run this ONCE after cloning, before Main/NO_CONN_001_wetland_pipeline.R.
# It is idempotent: files already present with the right size are skipped,
# so re-running after an interrupted download resumes sensibly.
#
# PRIVATE REPOSITORY: while the repo is private, GitHub requires
# authentication to download release assets. Set a token with
# `repo` scope first:
#     Sys.setenv(GITHUB_TOKEN = "ghp_...")     # or set it in the shell
# Once the repository is public no token is needed.
# ============================================================

# ---- where the caches live ----------------------------------
# Override either via environment variable if you fork the repository or
# publish a newer cache release.
REPO        <- Sys.getenv("CONN001_REPO", "Chimal93/wetland_condition_indicators")
RELEASE_TAG <- Sys.getenv("CONN001_RELEASE_TAG", "conn001-caches-v1")

if (!nzchar(REPO)) {
  stop("CONN001_REPO is empty. Set it to the GitHub repository holding the\n",
       "release, e.g. Sys.setenv(CONN001_REPO = \"owner/repo-name\").")
}

if (requireNamespace("rstudioapi", quietly = TRUE) && rstudioapi::isAvailable()) {
  setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
} else {
  cmd_args   <- commandArgs(trailingOnly = FALSE)
  file_match <- grep("^--file=", cmd_args)
  tried <- tryCatch({
    if (length(file_match) > 0) {
      setwd(dirname(normalizePath(sub("^--file=", "", cmd_args[file_match]))))
    } else {
      setwd(dirname(sys.frame(1)$ofile))
    }
    TRUE
  }, error = function(e) FALSE)
  if (!tried) message("Note: keeping current working directory (", getwd(), ").")
}

data_dir <- file.path("..", "Data")

# Asset filename -> destination folder. Release assets are a flat
# namespace, so the folder each belongs in is reconstructed here.
#
# Note the LUI_output rule keys on the .tif extension, NOT a "LUI_"
# prefix: that folder also holds ALI_count_*, BI_count_* and LCI_count_*
# (the three component indices the LUI is built from). A prefix rule
# silently dropped 9 of the 30 assets, which would only have surfaced as
# a mid-run failure much later.
dest_of <- function(asset) {
  if (grepl("\\.tif$", asset, ignore.case = TRUE))
    return(file.path(data_dir, "LUI_output"))
  if (grepl("^wetland_simplified_", asset))
    return(file.path(data_dir, "wetland_map_simplified"))
  if (grepl("_min_myr_distance_certified|_connectivity_full_", asset))
    return(file.path(data_dir, "connectivity_output_simplified"))
  NA_character_
}

# GitHub strips non-ASCII characters from Release asset names, so
# "wetland_simplified_Østlandet.gpkg" is stored as "..._Ostlandet.gpkg".
# The pipeline builds these paths from the Norwegian region names
# (regionlvl in Main), so the original filename has to be restored on
# download or Stage 6a/7a will not find its cache.
#
# Only these two files are affected: everything under
# connectivity_output_simplified/ is already written with ASCII region
# names (ostlandet/sorlandet) by the pipeline itself.
#
# Written with \u escapes rather than literal characters so this script
# behaves identically regardless of the encoding R reads it under.
restore_name <- function(asset) {
  O_slash <- "\u00D8"   # capital O-slash
  o_slash <- "\u00F8"   # lowercase o-slash
  if (identical(asset, "wetland_simplified_Ostlandet.gpkg"))
    return(paste0("wetland_simplified_", O_slash, "stlandet.gpkg"))
  if (identical(asset, "wetland_simplified_Sorlandet.gpkg"))
    return(paste0("wetland_simplified_S", o_slash, "rlandet.gpkg"))
  asset
}

token <- Sys.getenv("GITHUB_TOKEN")
api <- sprintf("https://api.github.com/repos/%s/releases/tags/%s", REPO, RELEASE_TAG)
hdr <- c(Accept = "application/vnd.github+json")
if (nzchar(token)) hdr <- c(hdr, Authorization = paste("Bearer", token))

cat("Querying release", RELEASE_TAG, "in", REPO, "...\n")
tmp <- tempfile(fileext = ".json")
ok <- tryCatch({ download.file(api, tmp, headers = hdr, quiet = TRUE, mode = "wb"); TRUE },
               error = function(e) { message("  failed: ", conditionMessage(e)); FALSE })
if (!ok) {
  stop("Could not read the release. If the repository is private, set GITHUB_TOKEN ",
       "to a token with `repo` scope. If it is public, check REPO/RELEASE_TAG are correct.")
}
rel <- jsonlite::fromJSON(tmp, simplifyVector = FALSE)
assets <- rel$assets
if (length(assets) == 0) stop("Release '", RELEASE_TAG, "' has no assets attached.")

cat("Found", length(assets), "asset(s).\n\n")
n_ok <- 0; n_skip <- 0; n_fail <- 0
for (a in assets) {
  name <- a$name; size <- a$size
  dest_dir <- dest_of(name)
  if (is.na(dest_dir)) {
    cat("  ? unrecognised asset, skipping:", name, "\n"); next
  }
  dir.create(dest_dir, recursive = TRUE, showWarnings = FALSE)
  dest <- file.path(dest_dir, restore_name(name))

  # Size match is the completeness check - a truncated download from an
  # interrupted run would otherwise look "present" and silently poison
  # every downstream stage.
  if (file.exists(dest) && file.size(dest) == size) {
    cat(sprintf("  = %-62s already present (%.0f MB)\n", name, size / 1e6))
    n_skip <- n_skip + 1; next
  }

  cat(sprintf("  > %-62s %.0f MB ...\n", name, size / 1e6))
  # The API asset URL (not browser_download_url) works for both public
  # and private repos, given an octet-stream Accept header.
  dl_hdr <- c(Accept = "application/octet-stream")
  if (nzchar(token)) dl_hdr <- c(dl_hdr, Authorization = paste("Bearer", token))
  res <- tryCatch({
    download.file(a$url, dest, headers = dl_hdr, quiet = TRUE, mode = "wb"); TRUE
  }, error = function(e) { message("    FAILED: ", conditionMessage(e)); FALSE })

  if (!res || !file.exists(dest) || file.size(dest) != size) {
    cat("    size mismatch or download failed - removing partial file\n")
    unlink(dest); n_fail <- n_fail + 1
  } else {
    n_ok <- n_ok + 1
  }
}

cat(sprintf("\nDone: %d downloaded, %d already present, %d failed.\n", n_ok, n_skip, n_fail))
if (n_fail > 0) {
  cat("Re-run this script to retry the failed assets - completed ones are skipped.\n")
} else {
  cat("Caches ready. You can now run Main/NO_CONN_001_wetland_pipeline.R.\n")
}
